env:
  - SYSCONFDIR="/tmp/ldapcherry/"
matrix:
  include:
    - python: "2.7"
      env: TEST_PEP8=1 SYSCONFDIR="/tmp/ldapcherry/"
language: python
python:
  - "2.7"
#  - "3.2"
#  - "3.3"
# command to install dependencies
#
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libcrack2-dev
install: 
  - "if [[ $TEST_PEP8 == '1' ]]; then pip install pep8; else pip install -e . ;fi"
  - pip install coveralls
# command to run tests
script: 
    - "if [[ $TEST_PEP8 == '1' ]]; then pep8 --repeat --show-source --exclude='.venv,.tox,dist,docs,build,*.egg,tests,misc,setup.py' . ;fi"
    - "if [[ $TEST_PEP8 != '1' ]]; then python setup.py test;fi"
after_success:
  - coveralls
after_failure:
  - sudo cat /var/log/syslog
